// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DSBlockMessage.proto

package DSBlockMessage

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ByteArray struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByteArray) Reset()         { *m = ByteArray{} }
func (m *ByteArray) String() string { return proto.CompactTextString(m) }
func (*ByteArray) ProtoMessage()    {}
func (*ByteArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{0}
}

func (m *ByteArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByteArray.Unmarshal(m, b)
}
func (m *ByteArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByteArray.Marshal(b, m, deterministic)
}
func (m *ByteArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteArray.Merge(m, src)
}
func (m *ByteArray) XXX_Size() int {
	return xxx_messageInfo_ByteArray.Size(m)
}
func (m *ByteArray) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteArray.DiscardUnknown(m)
}

var xxx_messageInfo_ByteArray proto.InternalMessageInfo

func (m *ByteArray) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProtoCommittee struct {
	Members              []*ByteArray `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProtoCommittee) Reset()         { *m = ProtoCommittee{} }
func (m *ProtoCommittee) String() string { return proto.CompactTextString(m) }
func (*ProtoCommittee) ProtoMessage()    {}
func (*ProtoCommittee) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{1}
}

func (m *ProtoCommittee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCommittee.Unmarshal(m, b)
}
func (m *ProtoCommittee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCommittee.Marshal(b, m, deterministic)
}
func (m *ProtoCommittee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCommittee.Merge(m, src)
}
func (m *ProtoCommittee) XXX_Size() int {
	return xxx_messageInfo_ProtoCommittee.Size(m)
}
func (m *ProtoCommittee) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCommittee.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCommittee proto.InternalMessageInfo

func (m *ProtoCommittee) GetMembers() []*ByteArray {
	if m != nil {
		return m.Members
	}
	return nil
}

type ProtoBlockBase struct {
	Blockhash            []byte                       `protobuf:"bytes,1,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	Cosigs               *ProtoBlockBase_CoSignatures `protobuf:"bytes,2,opt,name=cosigs,proto3" json:"cosigs,omitempty"`
	Timestamp            uint64                       `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ProtoBlockBase) Reset()         { *m = ProtoBlockBase{} }
func (m *ProtoBlockBase) String() string { return proto.CompactTextString(m) }
func (*ProtoBlockBase) ProtoMessage()    {}
func (*ProtoBlockBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{2}
}

func (m *ProtoBlockBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoBlockBase.Unmarshal(m, b)
}
func (m *ProtoBlockBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoBlockBase.Marshal(b, m, deterministic)
}
func (m *ProtoBlockBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoBlockBase.Merge(m, src)
}
func (m *ProtoBlockBase) XXX_Size() int {
	return xxx_messageInfo_ProtoBlockBase.Size(m)
}
func (m *ProtoBlockBase) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoBlockBase.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoBlockBase proto.InternalMessageInfo

func (m *ProtoBlockBase) GetBlockhash() []byte {
	if m != nil {
		return m.Blockhash
	}
	return nil
}

func (m *ProtoBlockBase) GetCosigs() *ProtoBlockBase_CoSignatures {
	if m != nil {
		return m.Cosigs
	}
	return nil
}

func (m *ProtoBlockBase) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ProtoBlockBase_CoSignatures struct {
	Cs1                  *ByteArray `protobuf:"bytes,1,opt,name=cs1,proto3" json:"cs1,omitempty"`
	B1                   []bool     `protobuf:"varint,2,rep,packed,name=b1,proto3" json:"b1,omitempty"`
	Cs2                  *ByteArray `protobuf:"bytes,3,opt,name=cs2,proto3" json:"cs2,omitempty"`
	B2                   []bool     `protobuf:"varint,4,rep,packed,name=b2,proto3" json:"b2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProtoBlockBase_CoSignatures) Reset()         { *m = ProtoBlockBase_CoSignatures{} }
func (m *ProtoBlockBase_CoSignatures) String() string { return proto.CompactTextString(m) }
func (*ProtoBlockBase_CoSignatures) ProtoMessage()    {}
func (*ProtoBlockBase_CoSignatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{2, 0}
}

func (m *ProtoBlockBase_CoSignatures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoBlockBase_CoSignatures.Unmarshal(m, b)
}
func (m *ProtoBlockBase_CoSignatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoBlockBase_CoSignatures.Marshal(b, m, deterministic)
}
func (m *ProtoBlockBase_CoSignatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoBlockBase_CoSignatures.Merge(m, src)
}
func (m *ProtoBlockBase_CoSignatures) XXX_Size() int {
	return xxx_messageInfo_ProtoBlockBase_CoSignatures.Size(m)
}
func (m *ProtoBlockBase_CoSignatures) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoBlockBase_CoSignatures.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoBlockBase_CoSignatures proto.InternalMessageInfo

func (m *ProtoBlockBase_CoSignatures) GetCs1() *ByteArray {
	if m != nil {
		return m.Cs1
	}
	return nil
}

func (m *ProtoBlockBase_CoSignatures) GetB1() []bool {
	if m != nil {
		return m.B1
	}
	return nil
}

func (m *ProtoBlockBase_CoSignatures) GetCs2() *ByteArray {
	if m != nil {
		return m.Cs2
	}
	return nil
}

func (m *ProtoBlockBase_CoSignatures) GetB2() []bool {
	if m != nil {
		return m.B2
	}
	return nil
}

type NodeDSBlock struct {
	Shardid              uint32                     `protobuf:"varint,1,opt,name=shardid,proto3" json:"shardid,omitempty"`
	Dsblock              *ProtoDSBlock              `protobuf:"bytes,2,opt,name=dsblock,proto3" json:"dsblock,omitempty"`
	Sharding             *ProtoShardingStructure    `protobuf:"bytes,4,opt,name=sharding,proto3" json:"sharding,omitempty"`
	Assignments          *ProtoTxSharingAssignments `protobuf:"bytes,5,opt,name=assignments,proto3" json:"assignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *NodeDSBlock) Reset()         { *m = NodeDSBlock{} }
func (m *NodeDSBlock) String() string { return proto.CompactTextString(m) }
func (*NodeDSBlock) ProtoMessage()    {}
func (*NodeDSBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{3}
}

func (m *NodeDSBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDSBlock.Unmarshal(m, b)
}
func (m *NodeDSBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDSBlock.Marshal(b, m, deterministic)
}
func (m *NodeDSBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDSBlock.Merge(m, src)
}
func (m *NodeDSBlock) XXX_Size() int {
	return xxx_messageInfo_NodeDSBlock.Size(m)
}
func (m *NodeDSBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDSBlock.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDSBlock proto.InternalMessageInfo

func (m *NodeDSBlock) GetShardid() uint32 {
	if m != nil {
		return m.Shardid
	}
	return 0
}

func (m *NodeDSBlock) GetDsblock() *ProtoDSBlock {
	if m != nil {
		return m.Dsblock
	}
	return nil
}

func (m *NodeDSBlock) GetSharding() *ProtoShardingStructure {
	if m != nil {
		return m.Sharding
	}
	return nil
}

func (m *NodeDSBlock) GetAssignments() *ProtoTxSharingAssignments {
	if m != nil {
		return m.Assignments
	}
	return nil
}

type ProtoDSBlock struct {
	Header               *ProtoDSBlock_DSBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Blockbase            *ProtoBlockBase             `protobuf:"bytes,2,opt,name=blockbase,proto3" json:"blockbase,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ProtoDSBlock) Reset()         { *m = ProtoDSBlock{} }
func (m *ProtoDSBlock) String() string { return proto.CompactTextString(m) }
func (*ProtoDSBlock) ProtoMessage()    {}
func (*ProtoDSBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{4}
}

func (m *ProtoDSBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoDSBlock.Unmarshal(m, b)
}
func (m *ProtoDSBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoDSBlock.Marshal(b, m, deterministic)
}
func (m *ProtoDSBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoDSBlock.Merge(m, src)
}
func (m *ProtoDSBlock) XXX_Size() int {
	return xxx_messageInfo_ProtoDSBlock.Size(m)
}
func (m *ProtoDSBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoDSBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoDSBlock proto.InternalMessageInfo

func (m *ProtoDSBlock) GetHeader() *ProtoDSBlock_DSBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ProtoDSBlock) GetBlockbase() *ProtoBlockBase {
	if m != nil {
		return m.Blockbase
	}
	return nil
}

type ProtoDSBlock_DSBlockHashSet struct {
	Shardinghash         []byte   `protobuf:"bytes,1,opt,name=shardinghash,proto3" json:"shardinghash,omitempty"`
	Txsharinghash        []byte   `protobuf:"bytes,2,opt,name=txsharinghash,proto3" json:"txsharinghash,omitempty"`
	Reservedfield        []byte   `protobuf:"bytes,3,opt,name=reservedfield,proto3" json:"reservedfield,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoDSBlock_DSBlockHashSet) Reset()         { *m = ProtoDSBlock_DSBlockHashSet{} }
func (m *ProtoDSBlock_DSBlockHashSet) String() string { return proto.CompactTextString(m) }
func (*ProtoDSBlock_DSBlockHashSet) ProtoMessage()    {}
func (*ProtoDSBlock_DSBlockHashSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{4, 0}
}

func (m *ProtoDSBlock_DSBlockHashSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoDSBlock_DSBlockHashSet.Unmarshal(m, b)
}
func (m *ProtoDSBlock_DSBlockHashSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoDSBlock_DSBlockHashSet.Marshal(b, m, deterministic)
}
func (m *ProtoDSBlock_DSBlockHashSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoDSBlock_DSBlockHashSet.Merge(m, src)
}
func (m *ProtoDSBlock_DSBlockHashSet) XXX_Size() int {
	return xxx_messageInfo_ProtoDSBlock_DSBlockHashSet.Size(m)
}
func (m *ProtoDSBlock_DSBlockHashSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoDSBlock_DSBlockHashSet.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoDSBlock_DSBlockHashSet proto.InternalMessageInfo

func (m *ProtoDSBlock_DSBlockHashSet) GetShardinghash() []byte {
	if m != nil {
		return m.Shardinghash
	}
	return nil
}

func (m *ProtoDSBlock_DSBlockHashSet) GetTxsharinghash() []byte {
	if m != nil {
		return m.Txsharinghash
	}
	return nil
}

func (m *ProtoDSBlock_DSBlockHashSet) GetReservedfield() []byte {
	if m != nil {
		return m.Reservedfield
	}
	return nil
}

type ProtoDSBlock_DSBlockHeader struct {
	Dsdifficulty         uint32                                     `protobuf:"varint,1,opt,name=dsdifficulty,proto3" json:"dsdifficulty,omitempty"`
	Difficulty           uint32                                     `protobuf:"varint,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Prevhash             []byte                                     `protobuf:"bytes,3,opt,name=prevhash,proto3" json:"prevhash,omitempty"`
	Leaderpubkey         *ByteArray                                 `protobuf:"bytes,4,opt,name=leaderpubkey,proto3" json:"leaderpubkey,omitempty"`
	Blocknum             uint64                                     `protobuf:"varint,5,opt,name=blocknum,proto3" json:"blocknum,omitempty"`
	Epochnum             uint64                                     `protobuf:"varint,6,opt,name=epochnum,proto3" json:"epochnum,omitempty"`
	Gasprice             *ByteArray                                 `protobuf:"bytes,7,opt,name=gasprice,proto3" json:"gasprice,omitempty"`
	Swinfo               *ByteArray                                 `protobuf:"bytes,8,opt,name=swinfo,proto3" json:"swinfo,omitempty"`
	Dswinners            []*ProtoDSBlock_DSBlockHeader_PowDSWinners `protobuf:"bytes,9,rep,name=dswinners,proto3" json:"dswinners,omitempty"`
	Hash                 *ProtoDSBlock_DSBlockHashSet               `protobuf:"bytes,10,opt,name=hash,proto3" json:"hash,omitempty"`
	Committeehash        []byte                                     `protobuf:"bytes,11,opt,name=committeehash,proto3" json:"committeehash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *ProtoDSBlock_DSBlockHeader) Reset()         { *m = ProtoDSBlock_DSBlockHeader{} }
func (m *ProtoDSBlock_DSBlockHeader) String() string { return proto.CompactTextString(m) }
func (*ProtoDSBlock_DSBlockHeader) ProtoMessage()    {}
func (*ProtoDSBlock_DSBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{4, 1}
}

func (m *ProtoDSBlock_DSBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoDSBlock_DSBlockHeader.Unmarshal(m, b)
}
func (m *ProtoDSBlock_DSBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoDSBlock_DSBlockHeader.Marshal(b, m, deterministic)
}
func (m *ProtoDSBlock_DSBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoDSBlock_DSBlockHeader.Merge(m, src)
}
func (m *ProtoDSBlock_DSBlockHeader) XXX_Size() int {
	return xxx_messageInfo_ProtoDSBlock_DSBlockHeader.Size(m)
}
func (m *ProtoDSBlock_DSBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoDSBlock_DSBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoDSBlock_DSBlockHeader proto.InternalMessageInfo

func (m *ProtoDSBlock_DSBlockHeader) GetDsdifficulty() uint32 {
	if m != nil {
		return m.Dsdifficulty
	}
	return 0
}

func (m *ProtoDSBlock_DSBlockHeader) GetDifficulty() uint32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *ProtoDSBlock_DSBlockHeader) GetPrevhash() []byte {
	if m != nil {
		return m.Prevhash
	}
	return nil
}

func (m *ProtoDSBlock_DSBlockHeader) GetLeaderpubkey() *ByteArray {
	if m != nil {
		return m.Leaderpubkey
	}
	return nil
}

func (m *ProtoDSBlock_DSBlockHeader) GetBlocknum() uint64 {
	if m != nil {
		return m.Blocknum
	}
	return 0
}

func (m *ProtoDSBlock_DSBlockHeader) GetEpochnum() uint64 {
	if m != nil {
		return m.Epochnum
	}
	return 0
}

func (m *ProtoDSBlock_DSBlockHeader) GetGasprice() *ByteArray {
	if m != nil {
		return m.Gasprice
	}
	return nil
}

func (m *ProtoDSBlock_DSBlockHeader) GetSwinfo() *ByteArray {
	if m != nil {
		return m.Swinfo
	}
	return nil
}

func (m *ProtoDSBlock_DSBlockHeader) GetDswinners() []*ProtoDSBlock_DSBlockHeader_PowDSWinners {
	if m != nil {
		return m.Dswinners
	}
	return nil
}

func (m *ProtoDSBlock_DSBlockHeader) GetHash() *ProtoDSBlock_DSBlockHashSet {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ProtoDSBlock_DSBlockHeader) GetCommitteehash() []byte {
	if m != nil {
		return m.Committeehash
	}
	return nil
}

type ProtoDSBlock_DSBlockHeader_PowDSWinners struct {
	Key                  *ByteArray `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  *ByteArray `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProtoDSBlock_DSBlockHeader_PowDSWinners) Reset() {
	*m = ProtoDSBlock_DSBlockHeader_PowDSWinners{}
}
func (m *ProtoDSBlock_DSBlockHeader_PowDSWinners) String() string { return proto.CompactTextString(m) }
func (*ProtoDSBlock_DSBlockHeader_PowDSWinners) ProtoMessage()    {}
func (*ProtoDSBlock_DSBlockHeader_PowDSWinners) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{4, 1, 0}
}

func (m *ProtoDSBlock_DSBlockHeader_PowDSWinners) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoDSBlock_DSBlockHeader_PowDSWinners.Unmarshal(m, b)
}
func (m *ProtoDSBlock_DSBlockHeader_PowDSWinners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoDSBlock_DSBlockHeader_PowDSWinners.Marshal(b, m, deterministic)
}
func (m *ProtoDSBlock_DSBlockHeader_PowDSWinners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoDSBlock_DSBlockHeader_PowDSWinners.Merge(m, src)
}
func (m *ProtoDSBlock_DSBlockHeader_PowDSWinners) XXX_Size() int {
	return xxx_messageInfo_ProtoDSBlock_DSBlockHeader_PowDSWinners.Size(m)
}
func (m *ProtoDSBlock_DSBlockHeader_PowDSWinners) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoDSBlock_DSBlockHeader_PowDSWinners.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoDSBlock_DSBlockHeader_PowDSWinners proto.InternalMessageInfo

func (m *ProtoDSBlock_DSBlockHeader_PowDSWinners) GetKey() *ByteArray {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ProtoDSBlock_DSBlockHeader_PowDSWinners) GetVal() *ByteArray {
	if m != nil {
		return m.Val
	}
	return nil
}

type ProtoShardingStructure struct {
	Shards               []*ProtoShardingStructure_Shard `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ProtoShardingStructure) Reset()         { *m = ProtoShardingStructure{} }
func (m *ProtoShardingStructure) String() string { return proto.CompactTextString(m) }
func (*ProtoShardingStructure) ProtoMessage()    {}
func (*ProtoShardingStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{5}
}

func (m *ProtoShardingStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoShardingStructure.Unmarshal(m, b)
}
func (m *ProtoShardingStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoShardingStructure.Marshal(b, m, deterministic)
}
func (m *ProtoShardingStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoShardingStructure.Merge(m, src)
}
func (m *ProtoShardingStructure) XXX_Size() int {
	return xxx_messageInfo_ProtoShardingStructure.Size(m)
}
func (m *ProtoShardingStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoShardingStructure.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoShardingStructure proto.InternalMessageInfo

func (m *ProtoShardingStructure) GetShards() []*ProtoShardingStructure_Shard {
	if m != nil {
		return m.Shards
	}
	return nil
}

type ProtoShardingStructure_Member struct {
	Pubkey               *ByteArray `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Peerinfo             *ByteArray `protobuf:"bytes,2,opt,name=peerinfo,proto3" json:"peerinfo,omitempty"`
	Reputation           uint32     `protobuf:"varint,3,opt,name=reputation,proto3" json:"reputation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProtoShardingStructure_Member) Reset()         { *m = ProtoShardingStructure_Member{} }
func (m *ProtoShardingStructure_Member) String() string { return proto.CompactTextString(m) }
func (*ProtoShardingStructure_Member) ProtoMessage()    {}
func (*ProtoShardingStructure_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{5, 0}
}

func (m *ProtoShardingStructure_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoShardingStructure_Member.Unmarshal(m, b)
}
func (m *ProtoShardingStructure_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoShardingStructure_Member.Marshal(b, m, deterministic)
}
func (m *ProtoShardingStructure_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoShardingStructure_Member.Merge(m, src)
}
func (m *ProtoShardingStructure_Member) XXX_Size() int {
	return xxx_messageInfo_ProtoShardingStructure_Member.Size(m)
}
func (m *ProtoShardingStructure_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoShardingStructure_Member.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoShardingStructure_Member proto.InternalMessageInfo

func (m *ProtoShardingStructure_Member) GetPubkey() *ByteArray {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *ProtoShardingStructure_Member) GetPeerinfo() *ByteArray {
	if m != nil {
		return m.Peerinfo
	}
	return nil
}

func (m *ProtoShardingStructure_Member) GetReputation() uint32 {
	if m != nil {
		return m.Reputation
	}
	return 0
}

type ProtoShardingStructure_Shard struct {
	Members              []*ProtoShardingStructure_Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ProtoShardingStructure_Shard) Reset()         { *m = ProtoShardingStructure_Shard{} }
func (m *ProtoShardingStructure_Shard) String() string { return proto.CompactTextString(m) }
func (*ProtoShardingStructure_Shard) ProtoMessage()    {}
func (*ProtoShardingStructure_Shard) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{5, 1}
}

func (m *ProtoShardingStructure_Shard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoShardingStructure_Shard.Unmarshal(m, b)
}
func (m *ProtoShardingStructure_Shard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoShardingStructure_Shard.Marshal(b, m, deterministic)
}
func (m *ProtoShardingStructure_Shard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoShardingStructure_Shard.Merge(m, src)
}
func (m *ProtoShardingStructure_Shard) XXX_Size() int {
	return xxx_messageInfo_ProtoShardingStructure_Shard.Size(m)
}
func (m *ProtoShardingStructure_Shard) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoShardingStructure_Shard.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoShardingStructure_Shard proto.InternalMessageInfo

func (m *ProtoShardingStructure_Shard) GetMembers() []*ProtoShardingStructure_Member {
	if m != nil {
		return m.Members
	}
	return nil
}

type ProtoTxSharingAssignments struct {
	Dsnodes              []*ByteArray                               `protobuf:"bytes,1,rep,name=dsnodes,proto3" json:"dsnodes,omitempty"`
	Shardnodes           []*ProtoTxSharingAssignments_AssignedNodes `protobuf:"bytes,2,rep,name=shardnodes,proto3" json:"shardnodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *ProtoTxSharingAssignments) Reset()         { *m = ProtoTxSharingAssignments{} }
func (m *ProtoTxSharingAssignments) String() string { return proto.CompactTextString(m) }
func (*ProtoTxSharingAssignments) ProtoMessage()    {}
func (*ProtoTxSharingAssignments) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{6}
}

func (m *ProtoTxSharingAssignments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTxSharingAssignments.Unmarshal(m, b)
}
func (m *ProtoTxSharingAssignments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTxSharingAssignments.Marshal(b, m, deterministic)
}
func (m *ProtoTxSharingAssignments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTxSharingAssignments.Merge(m, src)
}
func (m *ProtoTxSharingAssignments) XXX_Size() int {
	return xxx_messageInfo_ProtoTxSharingAssignments.Size(m)
}
func (m *ProtoTxSharingAssignments) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTxSharingAssignments.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTxSharingAssignments proto.InternalMessageInfo

func (m *ProtoTxSharingAssignments) GetDsnodes() []*ByteArray {
	if m != nil {
		return m.Dsnodes
	}
	return nil
}

func (m *ProtoTxSharingAssignments) GetShardnodes() []*ProtoTxSharingAssignments_AssignedNodes {
	if m != nil {
		return m.Shardnodes
	}
	return nil
}

type ProtoTxSharingAssignments_AssignedNodes struct {
	Receivers            []*ByteArray `protobuf:"bytes,1,rep,name=receivers,proto3" json:"receivers,omitempty"`
	Senders              []*ByteArray `protobuf:"bytes,2,rep,name=senders,proto3" json:"senders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProtoTxSharingAssignments_AssignedNodes) Reset() {
	*m = ProtoTxSharingAssignments_AssignedNodes{}
}
func (m *ProtoTxSharingAssignments_AssignedNodes) String() string { return proto.CompactTextString(m) }
func (*ProtoTxSharingAssignments_AssignedNodes) ProtoMessage()    {}
func (*ProtoTxSharingAssignments_AssignedNodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{6, 0}
}

func (m *ProtoTxSharingAssignments_AssignedNodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTxSharingAssignments_AssignedNodes.Unmarshal(m, b)
}
func (m *ProtoTxSharingAssignments_AssignedNodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTxSharingAssignments_AssignedNodes.Marshal(b, m, deterministic)
}
func (m *ProtoTxSharingAssignments_AssignedNodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTxSharingAssignments_AssignedNodes.Merge(m, src)
}
func (m *ProtoTxSharingAssignments_AssignedNodes) XXX_Size() int {
	return xxx_messageInfo_ProtoTxSharingAssignments_AssignedNodes.Size(m)
}
func (m *ProtoTxSharingAssignments_AssignedNodes) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTxSharingAssignments_AssignedNodes.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTxSharingAssignments_AssignedNodes proto.InternalMessageInfo

func (m *ProtoTxSharingAssignments_AssignedNodes) GetReceivers() []*ByteArray {
	if m != nil {
		return m.Receivers
	}
	return nil
}

func (m *ProtoTxSharingAssignments_AssignedNodes) GetSenders() []*ByteArray {
	if m != nil {
		return m.Senders
	}
	return nil
}

type ProtoPeer struct {
	Ipaddress            *ByteArray `protobuf:"bytes,1,opt,name=ipaddress,proto3" json:"ipaddress,omitempty"`
	Listenporthost       uint32     `protobuf:"varint,2,opt,name=listenporthost,proto3" json:"listenporthost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProtoPeer) Reset()         { *m = ProtoPeer{} }
func (m *ProtoPeer) String() string { return proto.CompactTextString(m) }
func (*ProtoPeer) ProtoMessage()    {}
func (*ProtoPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{7}
}

func (m *ProtoPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoPeer.Unmarshal(m, b)
}
func (m *ProtoPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoPeer.Marshal(b, m, deterministic)
}
func (m *ProtoPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoPeer.Merge(m, src)
}
func (m *ProtoPeer) XXX_Size() int {
	return xxx_messageInfo_ProtoPeer.Size(m)
}
func (m *ProtoPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoPeer.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoPeer proto.InternalMessageInfo

func (m *ProtoPeer) GetIpaddress() *ByteArray {
	if m != nil {
		return m.Ipaddress
	}
	return nil
}

func (m *ProtoPeer) GetListenporthost() uint32 {
	if m != nil {
		return m.Listenporthost
	}
	return 0
}

type ProtoDSNode struct {
	Pubkey               *ByteArray `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Peer                 *ByteArray `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProtoDSNode) Reset()         { *m = ProtoDSNode{} }
func (m *ProtoDSNode) String() string { return proto.CompactTextString(m) }
func (*ProtoDSNode) ProtoMessage()    {}
func (*ProtoDSNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{8}
}

func (m *ProtoDSNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoDSNode.Unmarshal(m, b)
}
func (m *ProtoDSNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoDSNode.Marshal(b, m, deterministic)
}
func (m *ProtoDSNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoDSNode.Merge(m, src)
}
func (m *ProtoDSNode) XXX_Size() int {
	return xxx_messageInfo_ProtoDSNode.Size(m)
}
func (m *ProtoDSNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoDSNode.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoDSNode proto.InternalMessageInfo

func (m *ProtoDSNode) GetPubkey() *ByteArray {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *ProtoDSNode) GetPeer() *ByteArray {
	if m != nil {
		return m.Peer
	}
	return nil
}

type ProtoDSCommittee struct {
	Dsnodes              []*ProtoDSNode `protobuf:"bytes,1,rep,name=dsnodes,proto3" json:"dsnodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProtoDSCommittee) Reset()         { *m = ProtoDSCommittee{} }
func (m *ProtoDSCommittee) String() string { return proto.CompactTextString(m) }
func (*ProtoDSCommittee) ProtoMessage()    {}
func (*ProtoDSCommittee) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1424e66b427e67, []int{9}
}

func (m *ProtoDSCommittee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoDSCommittee.Unmarshal(m, b)
}
func (m *ProtoDSCommittee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoDSCommittee.Marshal(b, m, deterministic)
}
func (m *ProtoDSCommittee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoDSCommittee.Merge(m, src)
}
func (m *ProtoDSCommittee) XXX_Size() int {
	return xxx_messageInfo_ProtoDSCommittee.Size(m)
}
func (m *ProtoDSCommittee) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoDSCommittee.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoDSCommittee proto.InternalMessageInfo

func (m *ProtoDSCommittee) GetDsnodes() []*ProtoDSNode {
	if m != nil {
		return m.Dsnodes
	}
	return nil
}

func init() {
	proto.RegisterType((*ByteArray)(nil), "DSBlockMessage.ByteArray")
	proto.RegisterType((*ProtoCommittee)(nil), "DSBlockMessage.ProtoCommittee")
	proto.RegisterType((*ProtoBlockBase)(nil), "DSBlockMessage.ProtoBlockBase")
	proto.RegisterType((*ProtoBlockBase_CoSignatures)(nil), "DSBlockMessage.ProtoBlockBase.CoSignatures")
	proto.RegisterType((*NodeDSBlock)(nil), "DSBlockMessage.NodeDSBlock")
	proto.RegisterType((*ProtoDSBlock)(nil), "DSBlockMessage.ProtoDSBlock")
	proto.RegisterType((*ProtoDSBlock_DSBlockHashSet)(nil), "DSBlockMessage.ProtoDSBlock.DSBlockHashSet")
	proto.RegisterType((*ProtoDSBlock_DSBlockHeader)(nil), "DSBlockMessage.ProtoDSBlock.DSBlockHeader")
	proto.RegisterType((*ProtoDSBlock_DSBlockHeader_PowDSWinners)(nil), "DSBlockMessage.ProtoDSBlock.DSBlockHeader.PowDSWinners")
	proto.RegisterType((*ProtoShardingStructure)(nil), "DSBlockMessage.ProtoShardingStructure")
	proto.RegisterType((*ProtoShardingStructure_Member)(nil), "DSBlockMessage.ProtoShardingStructure.Member")
	proto.RegisterType((*ProtoShardingStructure_Shard)(nil), "DSBlockMessage.ProtoShardingStructure.Shard")
	proto.RegisterType((*ProtoTxSharingAssignments)(nil), "DSBlockMessage.ProtoTxSharingAssignments")
	proto.RegisterType((*ProtoTxSharingAssignments_AssignedNodes)(nil), "DSBlockMessage.ProtoTxSharingAssignments.AssignedNodes")
	proto.RegisterType((*ProtoPeer)(nil), "DSBlockMessage.ProtoPeer")
	proto.RegisterType((*ProtoDSNode)(nil), "DSBlockMessage.ProtoDSNode")
	proto.RegisterType((*ProtoDSCommittee)(nil), "DSBlockMessage.ProtoDSCommittee")
}

func init() { proto.RegisterFile("DSBlockMessage.proto", fileDescriptor_3a1424e66b427e67) }

var fileDescriptor_3a1424e66b427e67 = []byte{
	// 887 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0xaa, 0xdb, 0x46,
	0x14, 0x46, 0xb2, 0xe2, 0x9f, 0x63, 0xfb, 0x12, 0x86, 0x52, 0x14, 0x37, 0xa4, 0x46, 0x94, 0xe0,
	0xf6, 0x36, 0x86, 0xeb, 0x90, 0x66, 0xd3, 0x52, 0xe2, 0x7b, 0x4b, 0x53, 0x4a, 0xca, 0x65, 0xdc,
	0x92, 0xf5, 0x58, 0x73, 0xae, 0x2d, 0x62, 0x4b, 0x62, 0x66, 0xec, 0xc4, 0x8b, 0x42, 0x9f, 0xa0,
	0x94, 0x3e, 0x43, 0x17, 0x7d, 0x91, 0xbe, 0x4f, 0x97, 0x5d, 0x96, 0x19, 0x8d, 0x2c, 0xc9, 0x38,
	0x96, 0xc9, 0x4e, 0x73, 0xe6, 0xfb, 0xce, 0xdf, 0x7c, 0x73, 0x46, 0xf0, 0xd1, 0xcd, 0x6c, 0xba,
	0x4a, 0xc2, 0x37, 0xaf, 0x50, 0x4a, 0xb6, 0xc0, 0x71, 0x2a, 0x12, 0x95, 0x90, 0x8b, 0xaa, 0x35,
	0xf8, 0x14, 0x3a, 0xd3, 0x9d, 0xc2, 0x17, 0x42, 0xb0, 0x1d, 0x21, 0xe0, 0x71, 0xa6, 0x98, 0xef,
	0x0c, 0x9d, 0x51, 0x8f, 0x9a, 0xef, 0xe0, 0x3b, 0xb8, 0xb8, 0xd5, 0xcc, 0xeb, 0x64, 0xbd, 0x8e,
	0x94, 0x42, 0x24, 0x4f, 0xa1, 0xb5, 0xc6, 0xf5, 0x1c, 0x85, 0xf4, 0x9d, 0x61, 0x63, 0xd4, 0x9d,
	0x3c, 0x18, 0x1f, 0x84, 0xda, 0x7b, 0xa4, 0x39, 0x32, 0xf8, 0xcb, 0xb5, 0x7e, 0x0c, 0x70, 0xca,
	0x24, 0x92, 0x87, 0xd0, 0x99, 0xeb, 0xc5, 0x92, 0xc9, 0xa5, 0x0d, 0x59, 0x18, 0xc8, 0x35, 0x34,
	0xc3, 0x44, 0x46, 0x0b, 0xe9, 0xbb, 0x43, 0x67, 0xd4, 0x9d, 0x5c, 0x1e, 0x06, 0xa9, 0x7a, 0x1b,
	0x5f, 0x27, 0xb3, 0x68, 0x11, 0x33, 0xb5, 0x11, 0x28, 0xa9, 0xa5, 0xea, 0x10, 0x2a, 0x5a, 0xa3,
	0x54, 0x6c, 0x9d, 0xfa, 0x8d, 0xa1, 0x33, 0xf2, 0x68, 0x61, 0x18, 0xfc, 0xe1, 0x40, 0xaf, 0x4c,
	0x23, 0x97, 0xd0, 0x08, 0xe5, 0x95, 0xc9, 0xe5, 0x64, 0x55, 0x1a, 0x45, 0x08, 0xb8, 0xf3, 0x2b,
	0xdf, 0x1d, 0x36, 0x46, 0xed, 0xa9, 0x7b, 0xdf, 0xa1, 0xee, 0xfc, 0x2a, 0x73, 0x30, 0x31, 0x91,
	0xea, 0x1c, 0x4c, 0x8c, 0x83, 0x89, 0xef, 0x95, 0x1c, 0x4c, 0x82, 0x7f, 0x1d, 0xe8, 0xfe, 0x94,
	0x70, 0xb4, 0x4c, 0xe2, 0x43, 0x4b, 0x2e, 0x99, 0xe0, 0x11, 0x37, 0x59, 0xf5, 0x69, 0xbe, 0x24,
	0x5f, 0x41, 0x8b, 0x4b, 0xd3, 0x2e, 0xdb, 0xa0, 0x87, 0x47, 0x1b, 0x64, 0x6d, 0x34, 0x07, 0x93,
	0x29, 0xb4, 0x33, 0x17, 0xf1, 0xc2, 0xf7, 0x0c, 0xf1, 0xf1, 0x51, 0xe2, 0xcc, 0x82, 0x66, 0x4a,
	0x6c, 0x42, 0xdd, 0x1e, 0xba, 0xe7, 0x91, 0x1f, 0xa1, 0xcb, 0xa4, 0x8c, 0x16, 0xf1, 0x1a, 0x63,
	0x25, 0xfd, 0x7b, 0xc6, 0xcd, 0xe7, 0x47, 0xdd, 0xfc, 0xfc, 0x4e, 0x3b, 0x8a, 0xe2, 0xc5, 0x8b,
	0x82, 0x40, 0xcb, 0xec, 0xe0, 0xf7, 0x16, 0xf4, 0xca, 0xa9, 0x92, 0x29, 0x34, 0x97, 0xc8, 0x38,
	0x0a, 0x7b, 0x10, 0x5f, 0x9c, 0x2a, 0x2c, 0xdf, 0x7b, 0x69, 0x18, 0xd4, 0x32, 0xc9, 0xd7, 0x56,
	0x5b, 0x73, 0x26, 0xd1, 0xf6, 0xe7, 0xd1, 0x69, 0x01, 0xd1, 0x82, 0x30, 0xf8, 0xcd, 0x81, 0xfc,
	0x9e, 0xbc, 0x64, 0x72, 0x39, 0x43, 0x45, 0x02, 0xe8, 0xe5, 0xe5, 0x97, 0xf4, 0x5a, 0xb1, 0x91,
	0xcf, 0xa0, 0xaf, 0xde, 0xc9, 0xac, 0x5c, 0x03, 0x72, 0x0d, 0xa8, 0x6a, 0xd4, 0x28, 0x81, 0x12,
	0xc5, 0x16, 0xf9, 0x5d, 0x84, 0x2b, 0x6e, 0xd4, 0xd2, 0xa3, 0x55, 0xe3, 0xe0, 0x3f, 0x0f, 0xfa,
	0x95, 0xd2, 0x74, 0x06, 0x5c, 0xf2, 0xe8, 0xee, 0x2e, 0x0a, 0x37, 0x2b, 0xb5, 0xb3, 0x7a, 0xa8,
	0xd8, 0xc8, 0x23, 0x80, 0x12, 0xc2, 0x35, 0x88, 0x92, 0x85, 0x0c, 0xa0, 0x9d, 0x0a, 0xdc, 0x9a,
	0xe4, 0xb2, 0xb0, 0xfb, 0x35, 0xf9, 0x06, 0x7a, 0x2b, 0x13, 0x29, 0xdd, 0xcc, 0xdf, 0xe0, 0xce,
	0x8a, 0xe3, 0x84, 0x88, 0x2b, 0x70, 0xed, 0xda, 0x34, 0x30, 0xde, 0xac, 0x8d, 0x20, 0x3c, 0xba,
	0x5f, 0xeb, 0x3d, 0x4c, 0x93, 0x70, 0xa9, 0xf7, 0x9a, 0xd9, 0x5e, 0xbe, 0x26, 0xcf, 0xa0, 0xbd,
	0x60, 0x32, 0x15, 0x51, 0x88, 0x7e, 0xab, 0x2e, 0xe4, 0x1e, 0x4a, 0xae, 0xa0, 0x29, 0xdf, 0x46,
	0xf1, 0x5d, 0xe2, 0xb7, 0xeb, 0x48, 0x16, 0x48, 0x7e, 0x81, 0x0e, 0xd7, 0x9f, 0xb1, 0x9e, 0x5c,
	0x1d, 0x33, 0xb9, 0x9e, 0x9f, 0x2f, 0xad, 0xf1, 0x6d, 0xf2, 0xf6, 0x66, 0xf6, 0x3a, 0xa3, 0xd3,
	0xc2, 0x13, 0xf9, 0x16, 0x3c, 0xd3, 0x4f, 0x38, 0x31, 0xa6, 0x0e, 0x3d, 0x66, 0xa2, 0xa2, 0x5e,
	0x2e, 0x88, 0x30, 0x1f, 0xae, 0xc6, 0x53, 0x37, 0x13, 0x44, 0xc5, 0x38, 0x58, 0x42, 0xaf, 0x9c,
	0x81, 0x1e, 0x35, 0xfa, 0x94, 0xea, 0x67, 0x95, 0x3e, 0x9c, 0x4b, 0x68, 0x6c, 0xd9, 0xca, 0x5e,
	0x84, 0x53, 0xe0, 0x2d, 0x5b, 0x05, 0xff, 0xb8, 0xf0, 0xf1, 0xf1, 0x11, 0x40, 0x6e, 0xa0, 0x69,
	0x14, 0x9f, 0x4f, 0xfe, 0x2f, 0xcf, 0x1b, 0x1d, 0x63, 0x63, 0xa1, 0x96, 0x3b, 0xf8, 0xd3, 0x81,
	0xe6, 0x2b, 0xf3, 0x2e, 0xe8, 0x63, 0xb4, 0x72, 0xab, 0x2d, 0xc4, 0x02, 0xb5, 0x60, 0x52, 0x44,
	0x61, 0xce, 0xbe, 0xb6, 0xa0, 0x3d, 0x54, 0x5f, 0x0d, 0x81, 0xe9, 0x46, 0x31, 0x15, 0x25, 0xb1,
	0x11, 0x7f, 0x9f, 0x96, 0x2c, 0x83, 0x5b, 0xb8, 0x67, 0xb2, 0x24, 0xdf, 0x1f, 0x3e, 0x6f, 0x4f,
	0xce, 0x2c, 0x32, 0x2b, 0xa9, 0x78, 0xf2, 0xfe, 0x76, 0xe1, 0xc1, 0x7b, 0x67, 0xa0, 0x7e, 0x45,
	0xb9, 0x8c, 0x13, 0x8e, 0xe7, 0xbc, 0xa2, 0x16, 0x49, 0x5e, 0x03, 0x98, 0x1e, 0x66, 0x3c, 0xf7,
	0x84, 0x86, 0x8f, 0xc5, 0x1c, 0x67, 0xdf, 0xc8, 0xf5, 0x0b, 0x23, 0x69, 0xc9, 0xd5, 0xe0, 0x57,
	0xe8, 0x57, 0x36, 0xc9, 0x73, 0xe8, 0x08, 0x0c, 0x31, 0xda, 0x9e, 0xf5, 0xcc, 0x17, 0x58, 0x5d,
	0x97, 0xc4, 0x98, 0x6b, 0x9a, 0x5b, 0x5b, 0x97, 0x45, 0x06, 0x2b, 0xe8, 0x98, 0xac, 0x6f, 0x11,
	0x85, 0x0e, 0x1d, 0xa5, 0x8c, 0x73, 0x81, 0x52, 0xd6, 0xcb, 0xa2, 0xc0, 0x92, 0xc7, 0x70, 0xb1,
	0x8a, 0xa4, 0xc2, 0x38, 0x4d, 0x84, 0x5a, 0x26, 0x52, 0xd9, 0x09, 0x78, 0x60, 0x0d, 0x12, 0xe8,
	0xda, 0x5b, 0xa9, 0x6b, 0xfd, 0x10, 0x0d, 0x3e, 0x01, 0x4f, 0x0b, 0xab, 0x5e, 0x7f, 0x06, 0x16,
	0xfc, 0x00, 0xf7, 0x6d, 0xc0, 0xe2, 0x2f, 0xea, 0xd9, 0xe1, 0xf9, 0x7f, 0xf2, 0x9e, 0xc9, 0xa1,
	0x73, 0xdc, 0x2b, 0x60, 0xde, 0x34, 0xbf, 0x71, 0x4f, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x7c,
	0x68, 0x67, 0x0d, 0xde, 0x09, 0x00, 0x00,
}
